name: one_hand
description: A One hand Flutter project for help.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

# == Dont use any package here this not good for me, Thanks ==  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  # For NavBar && dropdown list
  drop_down_list: ^0.0.6
  salomon_bottom_bar: ^3.3.2 
  # For toast ui here
  # fluttertoast: ^8.2.4
  # Save data here
  shared_preferences: ^2.0.6
  # APi && Network here
  connectivity_plus: ^3.0.2
  http: ^1.1.0
  # State managment here
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  # fonts 
  google_fonts: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/static/Inter-Regular.ttf
  # fonts:
  #   - family: Quicksand
  #     fonts:
  #       - asset: assets/fonts/quickSand/Quicksand-Regular.ttf
